
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-router-configmap
data:
  ROUTER_PORT: "5065"
  SERVICE_NAME: 'hexagots-user-router-api'
---

apiVersion: v1
kind: Secret
metadata:
  name: user-router-secret
type: Opaque
data:
  MONGODB_URI: 'bW9uZ29kYitzcnY6Ly9qYW5vb3BzaTpqYW5vb3BzaTk5OTlAY2xpY2tlcmNsdXN0ZXIubHR5Y2Vobi5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5'
  TOKEN_SECRET: 'U0VDUkVU'

---

apiVersion: v1
kind: Service
metadata:
  name: user-router-service
  labels:
    app: user-router-api
spec:
  type: NodePort
  selector:
    app: user-router-api
  ports:
    - protocol: TCP
      port: 5065
      targetPort: 5065
      nodePort: 30085

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-router-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-router-api
  template:
    metadata:
      labels:
        app: user-router-api
    spec:
      containers:
        - name: user-router-api
          image: janoopsi/user-router-api:latest
          ports:
            - containerPort: 5065
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: user-router-secret
                  key: MONGODB_URI
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-router-secret
                  key: TOKEN_SECRET
            - name: ROUTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-router-configmap
                  key: ROUTER_PORT
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-router-configmap
                  key: SERVICE_NAME
