apiVersion: v1
kind: ConfigMap
metadata:
  name: user-router-configmap
data:
  ROUTER_PORT: "5085"
  MONGODB_URI: "mongodb+srv://janoopsi:janoopsi9999@clickercluster.ltycehn.mongodb.net/?retryWrites=true&w=majority"
  SERVICE_NAME: 'hexagots-user-router-api'
  USER_REMOTE_REF: "user-remote-service"
  USER_REMOTE_PORT: "50051"
---

apiVersion: v1
kind: Secret
metadata:
  name: user-router-secret
type: Opaque
#data:
#  - MONGODB_URI: "mongodb+srv://janoopsi:janoopsi9999@clickercluster"

---

apiVersion: v1
kind: Service
metadata:
  name: user-router-service
  labels:
    app: user-router-api
spec:
  type: NodePort
  selector:
    app: user-router-api
  ports:
  - protocol: TCP
    port: 5085
    targetPort: 5085
    nodePort: 30085

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-router-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-router-api
  template:
    metadata:
      labels:
        app: user-router-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: user-router-api
        image: janoopsi/user-router-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5085
        env:
        - name: ROUTER_PORT
          valueFrom:
            configMapKeyRef:
              name: user-router-configmap
              key: ROUTER_PORT
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: user-router-configmap
              key: MONGODB_URI
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: user-router-configmap
              key: SERVICE_NAME
        - name: USER_REMOTE_REF
          valueFrom:
            configMapKeyRef:
              name: user-router-configmap
              key: USER_REMOTE_REF
        - name: USER_REMOTE_PORT
          valueFrom:
            configMapKeyRef:
              name: user-router-configmap
              key: USER_REMOTE_PORT
