version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-router

    ports:
      - '5085:5085'
    env_file: .env

    environment:
      - ROUTER_PORT=5085
    volumes:
      - ./:/var/data
    networks:
      - redpanda-network
networks:
  redpanda-network:
    external:
      name: redpanda-quickstart_redpanda_network