version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-remote
    ports:
      - '50051:50051'
    env_file: .env
    environment:
      - GRPC_PORT=50051
    volumes:
     - ./:/var/data
    networks:
      - redpanda-network
networks:
  redpanda-network:
    external:
      name: redpanda-quickstart_redpanda_network
